### ISSUE TITLE
ease~ with any circular function yields nan signal values

### ISSUE THREAD

**Issue by vichug** [Cycling74/ease#12]
Hey, trying the mc.ease~ from the helpfile and changing very few things ; if i select any circular easing function (in_circular, in_out_circular, out_circular) the output signal gives some nan values, which can't be downmixed and just sound very loud, whichever gain control operation i try to apply afterwards. From my understanding of easing function, this should not happen, right ? No reason why a circular easing function would give such an out-of-bounds result ? Especially since no other function does suche a thing. Well anyway here is the patch i used, which is nearly just the one from the helpfile, just tuning the phasor at an audio-rate frequency.

<pre><code>
----------begin_max5_patcher----------
1014.3ocuWsrrahCDcs8WAEq83R7xFmUyTy17GLUpTBgLnbAIJIgu1IUte6i
dfvfsuDhsuYgQXgPce5SqS27ikK7yXGwBeuO48edKV7ikKVXlROwht+uvuFd
DUAElk4W.Iz27W08j1JIAUBoTb0AHm.oR8hB5dLsslPqvRwvII4l8gk8s+J1
sOMPNrFKw7uhovrJrdEfyaBqU51kvtYsSIO0fsN+HWQPJnvJ+Ud99deo2DRT
IgV7UNFIsuylzj0fUdg6rCg5qAwf0.uunemetbo9xpYFXpQqweOGh5CN+JzG
4eSDBlvgi.ZeLdqcHwc8t7WJ9UkW37AI9nzAiZxwb1qzaCjvqARvsARvuAUM
EMssieRLnNMzQVOSTWwf40XgvKYtrWLXZTWRxywzIiCSh5fPCbCSMCVF+tQs
FZvB7UvtDxqYTBxSs8f.u..X8bI8nc+lr9jn0dRzb3SMDj9QvwpL6lRnfwey
6u0YeBu3YC13O1T7N3uwNDt6CB9RsBcQE9MEemLWru8OAzCshY6heHjKPrF7
rksBimV.NmHZpfmzPQOc76igcc4sar5x.Pud0cACDqtFqpjdIC9ukLl.6Aod
XnP4Ad6aoHIgQcqrhPwHVqsHrCw6YTIUUc0rE+iJCnZRItr1rtBv2pjEX5Pl
1VBx2sudz5IJkEYk2hB5R46hb2YDKyXAL24cGH3WOPDjLREQdZT5598BbmOX
rowjt3GC8BNOmCKDHNqpZHzPUDzKxRNqsnb371FVJu9ErO3v0OHqnlkOpEmL
FOW47Ca5wQXJlFuFYHd9ZElU.ctUnRRelJzAiHrPaN9cmh+9ZTZ.O6Vnh6a8
.wpXbGstMNHX6FM2FkrIcSjgkUcMkrSkpMfu+HUzhAlgMAOjhlNxj0JkmOiq
LlMV4lP4PLkw0omCQgJQkliMgJirjK2aPfJvl+uMMMLJQemNDklNNF0yMg8p
L3BH5jd998ZxF9GsRM8DEuCDt5F2LztCUcBmy2In0d1CQ3K7mADbz6l3ux9y
DZcNPFD8RgIJNbGuAeGaU+iB6NY3tNhvMaqQf9hu1xrg54GmEHXsbjy+bo5d
mCO4XgjPgF0+yKZ7Z5UUBtYl2rs7LLbjcMOjclC.ieB1Y6brSvSvPZA3+LVZ
VIGgw2N6.7XlFLCSeQjXv2F8P1V+MH+5TymQNSzbNDr8JCYO0CaZNf4htEar
gRk+aVAwzUl+RnryM.3yw5tWrq2nZ4C4JYGoRyokaaL33Fa6q95lI3zVRW3T
gNkIExSUWpzz2SgD1XETU3XOTUbaL3G1vnBYeFJYdelTTp0FsXaUWriq5R0X
oAEjrUKc4UtPfohldSEMcRzlBeK+4x+2hBT0w
-----------end_max5_patcher-----------
</code></pre>

**Comment by tap** [comment]
Thanks @vichug !

I'll get to work on fixing this right now. 

I think the actual code would be a call to `max` rather than a call to `min`, as the `min` of a negative number and 0 would actually be the negative number :-). This was super helpful that you pin pointed exactly where the problem is!

**Comment by tap** [comment]
Will be updating in the Package Manager shortly...
